version: '3.7'

services:
  # docker exec -i db pg_dump -U postgres -d postgres -Z9 -Fc > dump.sql
  # docker exec -i db pg_restore -U postgres -d postgres < ~/dump.sql
  db:
    image: postgres:12-alpine
    env_file:
      - backend/.envfile
    volumes:
      - db-data:/var/lib/postgresql/data
    container_name: db
    ports:
      - 5432:5432
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '1'


volumes:
  db-data:
  redis: